### PR TITLE
+Fremont County WY council districts

### PR DESCRIPTION
**Pull request by rsimoes**

### CODE REVIEW

**Comment by jdmgoogle** [comment]
The changes to the WY file look good, but do you know why GitHub thinks there are changes to the other 8,010 lines in the country-us.csv file?

large_diff

**Comment by jpmckinney** [comment]
It's possible that newline characters were changed.

**Comment by rsimoes** [comment]
For some reason the country-us.csv file had a mix of `\n` and `\r\n` breaks. I'm not sure how that would have been possible without prior manual editing.

**Comment by jdmgoogle** [comment]
What do they have now?

**Comment by jpmckinney** [comment]
@jdmgoogle If compile.py was run, then I assume this PR has the intended line terminators. (This can be verified by making a local copy of the branch and re-running it.)

**Comment by rsimoes** [comment]
CRLF, which is in line with RFC 4180. I think that's the default setting for Python's core `csv` library.

**Comment by jdmgoogle** [comment]
SGTM. Approved.

**Pull request merged**
