### PR TITLE
Renaming Shannon County to Oglala Lakota County (South Dakota)

### PR DESCRIPTION
**Pull request by afsmythe**
Recently became aware that Shannon County has been renamed to Oglala Lakota in South Dakota. 

Source: https://en.wikipedia.org/wiki/Oglala_Lakota_County,_South_Dakota

Question: does this change account for all the necessary changes to files? Any input is appreciated, thanks!

### CODE REVIEW

**Comment by jdmgoogle** [comment]
You'll need to re-run the compile script to update the country-us.csv file as well.

**Comment by afsmythe** [comment]
Apologies for the noise. I'm getting this error and am unable to locate the cause. 

```
ERROR: 1 unknown parents
   ocd-division/country:us/state:sd/county:oglala_lakota 
```

**Comment by jdmgoogle** [comment]
You'll need to update the name in `identifiers/country-us/census_autogenerated/us_census_places.csv` as well

**Review by jdmgoogle — APPROVED** [review]

**Comment by jdmgoogle** [comment]
Paging @djbridges or @jamesturk or @jpmckinney or someone else with approver power. :)

**Comment by jpmckinney** [comment]
Not sure how US wants to do change management, but renaming can be accompanied by a sameAs column to preserve the old OCDID. Otherwise, feel free to merge.

**Comment by afsmythe** [comment]
Thanks! I'll wait to merge until the end of the day in case there's a preference for using `sameAs`.

**Pull request merged**
