### PR TITLE
Add OCD-ID's of NI

### PR DESCRIPTION
**Pull request by sguenther85**

### CODE REVIEW

**Comment by sguenther85** [comment]
Hi together,

@jpmckinney @azuser @jloutsenhizer.

Can somebody again please review the ocd-ids.
The election in nicaragua is approximately at the end of this year.
Let me know if anything looks incorrect.

Thanks. 
Best Steve

**Review by jpmckinney — APPROVED** [review]

**Comment by sguenther85** [comment]
Anybody else maybe time to review or/and approve?

**Comment by sguenther85** [comment]
@jloutsenhizer @azuser

**Comment by azuser** [comment]
> @jloutsenhizer @azuser

LGTM. Thanks :)

**Pull request merged**
