### PR TITLE
add New Zealand and electorates

### PR DESCRIPTION
**Pull request by aaronpdennis**
/cc: @dmcglone

This pull request:

1. Adds New Zealand
2. Adds OCD Division IDs for New Zealand's 64 general electorates and 7 maori electorates

Discussion of conventions for New Zealand electorates: https://groups.google.com/forum/#!topic/open-civic-data/4ar3ClCXtjk

### CODE REVIEW

**Comment by jpmckinney** [comment]
Are the official names really "New Zealand House of Representatives Te Tai Tokerau Maori electorate" or just "Te Tai Tokerau" ? Can't "New Zealand House of Representatives" and "Maori electorate" be determined based on the type and hierarchy of each division?

**Comment by aaronpdennis** [comment]
@jpmckinney Perhaps. I was using the conventions in [country-au/federal_electorates](https://github.com/opencivicdata/ocd-division-ids/blob/master/identifiers/country-au/federal_electorates.csv) as a reference. Maybe these New Zealand electorate names should just be "House of Representatives Te Tai Tokerau Maori electorate"?

**Comment by jpmckinney** [comment]
The other countries aren't all good examples :)

I would typically go with "Te Tai Tokerau" because in conversation, in news articles, etc. I doubt people say things like "There will be by-elections in the House of Representatives Te Tai Tokerau Maori electorate and the House of Representatives Auckland Central General electorate." Seems more likely to say, "There will be by-elections in Te Tai Tokerau and Auckland Central."

**Comment by aaronpdennis** [comment]
names have been trimmed

**Comment by jpmckinney** [comment]
Looks good! I checked quickly whether there are any standard abbreviations/identifiers for electorates (to use in the type ID), but it doesn't look like it.

**Pull request merged**
