### PR TITLE
Fix Gatineau subdivisions

### PR DESCRIPTION
**Pull request by rafe-murray**
Added a 19th district (district 5) and changed some of the names of districts to reflect what is currently on the Gatineau municipal site: https://www.gatineau.ca/portail/default.aspx?p=guichet_municipal/conseil_municipal&requete=coun&ref=haut-de-page

### CODE REVIEW

**Review by evannjw — APPROVED** [review]

**Comment by HKSenior** [comment]
@rafe-murray friendly ping to resolve all merge conflicts.

**Comment by rafe-murray** [comment]
Thanks @HKSenior I've resolved them now.

**Comment by jpmckinney** [comment]
For QC, I typically email https://dgeq.org for a file for all municipalities in the province. I've tried my old contact now.

**Comment by jpmckinney** [comment]
I received the file. I'll try to process it sometime soon.

**Comment by jpmckinney** [comment]
Here are the IDs and names from the govt file. @rafe-murray Maybe in the scraper just remove the "de l'", etc.?


```
1 Aylmer 
2 Lucerne
3 Deschênes
4 Plateau
5 Mitigomijokan
6 Manoir-des-Trembles--Val-Tétreau 
7 Hull-Wright
8 Parc-de-la-Montagne--Saint-Raymond 
9 Orée-du-Parc
10 Limbour
11 Touraine 
12 Pointe-Gatineau
13 Carrefour-de-l'Hôpital 
14 Versant
15 Bellevue 
16 Lac-Beauchamp
17 Rivière-Blanche
18 Masson-Angers
19 Buckingham 
```

**Comment by rafe-murray** [comment]
I added a new commit to make the names consistent with those ones

**Comment by jpmckinney** [comment]
Hi, I realized there was an error in the hyphenation. Please replace `--` with `—` (em-dash).

**Comment by rafe-murray** [comment]
The dashes should be correct now

**Pull request merged**
