### PR TITLE
Update German Lander (state) and Wahlkreise (constituency) OCD-IDs

### PR DESCRIPTION
**Pull request by jdmgoogle**
This PR does 4 things:

1. Fixes the "land" (state) and "wahlkreise" (constituency) district OCD-IDs.
1a. The OCD-IDs themselves did not follow [proper naming/casing/special character guidelines](http://docs.opencivicdata.org/en/latest/proposals/0002.html)
1b. All of the constituencies were under a single Lander (state)
2. Make the canonical OCD-IDs use "state" and "cd", and add the (corrected) previous ones as aliases.
3. The canonical constituency districts now use the official [government-assigned numbers](https://www.bundeswahlleiter.de/en/bundestagswahlen/2017/wahlkreiseinteilung.html).
4. All OCD-IDs are sorted for easier scanning/finding.

I did not update the top-level country-de.csv file since it appears that @jpmckinney (or someone) has a script they use to update those countries. Let me know if this is incorrect and I can update the top-level file myself.

### CODE REVIEW

**Comment by jpmckinney** [comment]
@jdmgoogle The script is described at https://github.com/opencivicdata/ocd-division-ids/tree/master/scripts#readme

I thought `cd` stood for `Congressional district`, in US anyway. https://github.com/opencivicdata/ocd-division-ids/blob/master/identifiers/country-us/README.md#cd

Are 'state' and 'constituency district' the correct translations of 'land' and 'wahlkreise'? There's no requirement for consistency of types across countries.

**Comment by jdmgoogle** [comment]
@jpmckinney Ran the script. It caught a few errors and the fact that I'd swapped the state-level alias columns.

And yes, "state" and "constituency district" are correct translations:
https://en.wikipedia.org/wiki/List_of_Bundestag_constituencies
https://en.wikipedia.org/wiki/States_of_Germany

**Comment by jdmgoogle** [comment]
Friendly ping @jpmckinney

**Comment by jpmckinney** [comment]
Thanks!

**Pull request merged**
