### PR TITLE
+833 new divisions across 30 states

### PR DESCRIPTION
**Pull request by rsimoes**
This is a small subset of the divisions created during CTCL's 2016 Ballot Information Project. It contains no new district types. There was also a fair amount of diff noise in identifiers/country-us.csv from running compile.py, which caused line terminators to change from LF to CRLF.

### CODE REVIEW

**Comment by jpmckinney** [comment]
@jamesturk Who did we decide governs the US division IDs?

**Comment by jamesturk** [comment]
I think tentatively we'd said that @djbridges was working to figure that out among interested parties, I believe @rsimoes you work w/ Donny right?  I just scanned this and it looks superficially OK

**Comment by lbirdpew** [comment]
Hi,

Is there an ETA on this being approved?  Just curious

**Comment by jamesturk** [comment]
@rsimoes any word on a governance process for these?  I don't want to hold these up, they look reasonable and I know you all are using them in production but wasn't sure if we're close to a review process for these or not

**Pull request closed without merging**
