### PR TITLE
Added 10 new seats for the Japan

### PR DESCRIPTION
**Pull request by MarcinMisztalTR**
- added 10 new seats for the Japan general election

Hello,
According to [https://en.wikipedia.org/wiki/Next_Japanese_general_election](https://en.wikipedia.org/wiki/Next_Japanese_general_election) there will be 10 new seats introduced in Japan for that election:
[Tokyo-26th](https://en.wikipedia.org/wiki/Tokyo_26th_district)
[Tokyo-27th](https://en.wikipedia.org/wiki/Tokyo_27th_district)
[Tokyo-28th](https://en.wikipedia.org/wiki/Tokyo_28th_district)
[Tokyo-29th](https://en.wikipedia.org/wiki/Tokyo_29th_district)
[Tokyo-30th](https://en.wikipedia.org/wiki/Tokyo_30th_district)
[Kanagawa-19th](https://en.wikipedia.org/wiki/Kanagawa_19th_district)
[Kanagawa-20th](https://en.wikipedia.org/wiki/Kanagawa_20th_district)
[Saitama-16th](https://en.wikipedia.org/w/index.php?title=Saitama_16th_district&action=edit&redlink=1)
[Aichi-16th](https://en.wikipedia.org/w/index.php?title=Aichi_16th_district&action=edit&redlink=1)
[Chiba-14th](https://en.wikipedia.org/w/index.php?title=Chiba_14th_district&action=edit&redlink=1)

Please let me know if more details are needed. Thank you.

### CODE REVIEW

**Review by evannjw — COMMENTED** [review]
I would suggest adding a validFrom column and adding 2025 to the new districts as it looks like the changes aren't in effect until after the election some time in 2025. It also looks like 10 districts are going to be eliminated so consider adding a validThrough column with the year 2025 to the districts that are being removed.
https://open-civic-data.readthedocs.io/en/latest/proposals/0002.html#:~:text=has%20multiple%20identifiers.-,validThrough,-The%20date%20on

**Comment by MarcinMisztalTR** [comment]
> I would suggest adding a validFrom column and adding 2025 to the new districts as it looks like the changes aren't in effect until after the election some time in 2025. It also looks like 10 districts are going to be eliminated so consider adding a validThrough column with the year 2025 to the districts that are being removed. https://open-civic-data.readthedocs.io/en/latest/proposals/0002.html#:~:text=has%20multiple%20identifiers.-,validThrough,-The%20date%20on

Hello,
Thank you for response. I've added validFrom (set to 2025) for:
	1	Tokyo-26th
	2	Tokyo-27th
	3	Tokyo-28th
	4	Tokyo-29th
	5	Tokyo-30th
	6	Kanagawa-19th
	7	Kanagawa-20th
	8	Saitama-16th
	9	Aichi-16th
	10	Chiba-14th
and validThrough (set to 2025) for:
	1	Hiroshima-7th
	2	Miyagi-6th
	3	Niigata-6th
	4	Fukushima-5th
	5	Okayama-5th
	6	Shiga-4th
	7	Yamaguchi-4th
	8	Ehime-4th
	9	Nagasaki-4th
	10	Wakayama-3rd

**Comment by jloutsenhizer** [comment]
This looks good overall.

I'm not sure if we should have the 2025 date set for validFrom and validThrough since, as I understand it, the next election where these changes take effect could happen before 2025 if the government is dissolved:

- https://en.wikipedia.org/wiki/Next_Japanese_general_election
- https://en.wikipedia.org/wiki/House_of_Representatives_(Japan)#Differences_between_the_Upper_and_Lower_Houses

@jpmckinney Any thoughts here?

**Comment by jpmckinney** [comment]
@jloutsenhizer Yes, we typically set the validFrom/validThrough to the election date.

One option is to not add the new boundaries (and not set validThrough dates on the soon-to-be removed boundaries) until an election date is set.

**Comment by MarcinMisztalTR** [comment]
Hello,
I've removed validThrough values from single_member_constituencies.csv. Current state should be:

validFrom (set to 2025) for:
- Tokyo-26th
- Tokyo-27th
- Tokyo-28th
- Tokyo-29th
- Tokyo-30th
- Kanagawa-19th
- Kanagawa-20th
- Saitama-16th
- Aichi-16th
- Chiba-14th

**Review by jpmckinney — APPROVED** [review]

**Comment by jpmckinney** [comment]
Looks good. Yes, once a date is set, we can add precision to validFrom, and fill in validThrough.

**Pull request merged**
