### PR TITLE
ca: Create new files for current, abolished and renamed OCD-IDs

### PR DESCRIPTION
**Pull request by jpmckinney**
This PR implements a naming policy co-created with @evannjw in #323.

In brief:

* All current divisions are given an ID, based on their name.
* All divisions that are abolished according to the Library of Parliament are given an ID, based on their name.
* If multiple current/abolished divisions have the same ID, later divisions are suffixed with the validFrom year.
* All divisions that were renamed according to the Library of Parliament are aliases (sameAs) to another ID.
* A province/territory:id pair is prefixed to the ed:id pair, since two provinces can contain the same district name.
* The most recent ID is the "canonical" ID. Previous renames are aliased to it. This ensures that renamings to respect language, culture, etc. (e.g. Three Rivers -> Trois Rivières) are reflected in the dataset, without giving primacy to the old name that might be colonial, etc.

To complete the PR:

* [ ] Add missing sameAs aliases (about 60 left to resolve either via code or manually)
* [ ] Do the TODOs in the code (also remove validFrom,validThrough from aliases CSV)
* [ ] Add sameAs aliases between the existing OCD-IDs and these new ones

### CODE REVIEW

**Comment by jpmckinney** [comment]
Sounds good. Yes, I wanted to get agreement on what I had so far before completing the TODOs.

We can rename the old files (those IDs will be aliases to the new ones), and document the naming policy in the readme.

The Ruby scripts for those IDs would be removed, as the Python script is now responsible for federal IDs.

**Comment by jpmckinney** [comment]
I can work on the TODOs in the Python script, if you can help with aliasing the current federal IDs (`ca_federal_electoral_districts-2013.csv` should be easy, `ca_federal_electoral_districts.csv` probably requires a lookup that accounts for name, validFrom, validThrough).

**Comment by evannjw** [comment]
Sounds good, I'll also update the README and rename/clean up old files.

**Comment by evannjw** [comment]
I don't seem to have access to push to this branch/repo. Here is a file containing aliases of current federal IDs. 
[aliases.csv](https://github.com/opencivicdata/ocd-division-ids/files/9964507/aliases.csv)

**Comment by jpmckinney** [comment]
@evannjw I don't have much time this week for this PR, so if you can help with the other items, please have a look.

**Comment by evannjw** [comment]
Sure I can wrap up the remaining TODOs here

**Comment by evannjw** [comment]
Hi sorry, haven't actually had time to work on this, should be able to get to this tomorrow/early next week

**Comment by jpmckinney** [comment]
Replaced by #327

**Pull request closed without merging**
