### PR TITLE
Update Australian federal electorate ids for 2016

### PR DESCRIPTION
**Pull request by GeoWill**
There were some changes to the federal electorates in 2016:
Burt WA - CREATED
Charlton NSW - ABOLISHED
Throsby NSW RENAMED Whitlam NSW
Fraser ACT RENAMED Fenner ACT

This commit makes the appropriate changes.

### CODE REVIEW

**Comment by jpmckinney** [comment]
@GeoWill Can you share the source/evidence for the changes?

**Comment by GeoWill** [comment]
3 Years ago, so inevitably the links I had then (See: https://github.com/everypolitician/proto-commons-australia) all point to dead sites. However there seems to be pretty comprehensive tracking of this stuff here: https://www.aec.gov.au/Electorates/Redistributions/dates.htm which leads to some sort of legal instrument on https://www.legislation.gov.au/ which I guess is suitable.

Bit of poking around yields: 
NSW: https://www.legislation.gov.au/Details/C2016G00277
ACT: https://www.legislation.gov.au/Details/C2016G00114
WA: https://www.legislation.gov.au/Details/C2016G00078

However there have been a number of redistributions since then, so no doubt more has changed in the mean time...

**Comment by jpmckinney** [comment]
Ah - Australia redistributes regularly! Canada only does it every 10 years.

Should I close the PR or do you anticipate updating it? I'm not sure if it's worth merging if it's already outdated.

**Comment by GeoWill** [comment]
It is _more_ right :grin:. More seriously I don't think I'm going to be the one to update it, so probably best to close. :+1:

**Comment by jpmckinney** [comment]
I just noticed a typo (no `/` after `act`), so I'll just close :)

**Pull request closed without merging**
